### ISSUE TITLE
Release 2.7.0.Final is missing on Github repository

### ISSUE THREAD

**Issue by oscerd** [openshift/openshift-java-client#219]
Hi,

Just a note: the 2.7.0.Final is released on maven central, but on the github repository there isn't the same release.

Andrea

**Comment by adietish** [comment]
we're ahead of it in master, master is at 2.8.0-SNAPSHOT which we didnt release yet.
On a side-note I have to point out that developement on this slowed down since we moved over to a OpenShift v3 java client library.

**Comment by oscerd** [comment]
Hi Andrè,

No. I was just watching at the latest release on github and I've noted that is 2.6.0.Final (https://github.com/openshift/openshift-java-client/releases) while on Maven Central the latest is 2.7.0.Final.  It was just a reporting.

**Comment by adietish** [comment]
oh, goot catch, thanks! Fixing.

**Comment by adietish** [comment]
tagged and pushed.
