### ISSUE TITLE
Support for Members & Teams

### ISSUE THREAD

**Issue by blinkfish** [openshift/openshift-java-client#222]
Add support for Managing Members/Teams of Domains/Applications.  See Chapter 9: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/pdf/REST_API_Guide/OpenShift_Enterprise-2-REST_API_Guide-en-US.pdf

**Comment by adietish** [comment]
I fully agree that his would be a nice enhancement. Nevertheless I fear that we will not be able to provide this, but we'd very gladly accept contributions:
The effort to do the lib in my team was mainly driven by the needs of the Eclipse tooling. Whatever Eclipse needed to be able to do was implemented in the lib. The goal for the Eclipse tooling was to provide developer tooling, devops things were left to the cmd-line rhc. Managing members/teams thus isnt typically in our focus. Furthermore we now moved on to do a lib and tooling for OpenShift v3 which leaves even less time for any enhancement in the v2 lib.
On the other hand if you're working in a company that is using OpenShift Enterprise there are chances that you can convince our management that this needs to be done. Typically your management would then talk to the Red Hat contact in your company and pass the message along.

**Comment by blinkfish** [comment]
Thanks, appreciate the response - I thought this might be the case.  Good to know that the project is willing to accept contributions, I'll definitely consider this avenue.

**Comment by adietish** [comment]
oh yes, we'd love to get contribs. Looking forward to it :)
