### ISSUE TITLE
Specifying the target branch of a git repository

### ISSUE THREAD

**Issue by kiuby88** [openshift/openshift-java-client#223]
Web console allows to select a target branch for cloning a repository.
I think it could be interesting to add this feature to the java client.
WDYT?

**Comment by adietish** [comment]
I'm not sure that I get you right: you're talking of the url for downloadable cartridges, right? So you'd like to be able to provide the library with the git url and branch for downloadable cartridges?

**Comment by kiuby88** [comment]
Hi @adietish, thanks for your reply

I am talking about the git repositories of the applications which will be deployed. Using the web console, you can specify the git url where the application's source code is stored and the branch which will be cloned, for example origin/any-feature-wip.

**Comment by adietish** [comment]
Hi @kiuby88 

so you're talking of OpenShift v3, not v2, right?

**Comment by kiuby88** [comment]
Hi,

I am talking of v2, but I think it ma be useful for any version.
In any case, I think I should migrate to OpenShift v3, right?

**Comment by adietish** [comment]
@kiuby88 hmm, so I unfortunately still dont fully follow. can you please point me to the (screenshot maybe) where you can provide this? Is this the application code (application template code) 
that you get when creating your openshift application?
![application-source](https://cloud.githubusercontent.com/assets/25126/8497981/36235ee0-2182-11e5-9d39-412250531962.png)

Yes at some point migrating to v3 will be the way to go since it'll replace v2 at some point in mid-term future. On the other hand v3 is a complete rewrite, a completely different beast and we're early with it. It's more powerful but not as comfortable/cozy as v2 yet.

**Comment by kiuby88** [comment]
It is a snapshot of the OpenShift web console. You can specify the git repository where the application is stored and the branch that will be used, instead of use the master (HEAD) branch.

<img width="893" alt="captura de pantalla 2015-07-04 a la s 11 52 14" src="https://cloud.githubusercontent.com/assets/3704424/8507437/314c4e42-2243-11e5-9dc7-91ecb67fc916.png">

Using the client lib, you can just specify the git repository, and I think that it could be interesting to specify the branch for the java-client-lib too.

```
new ApplicationBuilder(domain)
                .setName(applicationName)
                .setStandaloneCartridge(cartridge)
                .setApplicationScale(scale1)
                .setInitialGitUrl(gitRepositoryUrl)
                .build();
```

For example adding something as `.setGitUrlBranch(branch)`.

Once, thanks a lot for your reply.

**Comment by adietish** [comment]
in the above screenshot from web-ui "custom-env" is the branch that you get your application source from, right?
Sounds like a small but very useful enhancement. And yes, your suggestion for the API sounds good.
The last impediment we have is the very little time that's left for maintenance in OpenShift v2. If we'd assist you, is this something you'd like to contribtute? That would be awesome if possible.

**Comment by kiuby88** [comment]
Of course @adietish. I'd love developing this feature, I will take a look and write you.

**Comment by adietish** [comment]
awesome! looking forward to it. Whenever needed feel free to ping me :) (I'm always on irc on #jbosstools)
