### ISSUE TITLE
Documentation is outdated

### ISSUE THREAD

**Issue by rjahn** [openshift/openshift-java-client#226]
Your README and all example links contain examples with OpenShiftConnectionFactory(). This class is deprecated and ConnectionBuilder should be used.

It's not easy without reading your source code. I miss test-cases or library examples.

Something like this would help other users:

```
ConnectionBuilder cb = new ConnectionBuilder();
CredentialsConnectionBuilder ccb = cb.credentials(username, password);
IOpenShiftConnection connection = ccb.create();
```

**Comment by MitchTalmadge** [comment]
This is almost a year old, but still relevant. Documentation would be great. I've had to figure out everything from trial-and-error, looking through code, etc. The example above was very useful. I'm not asking for exhaustive documentation, just a few examples of how to do certain actions.
