### ISSUE TITLE
Application Status

### ISSUE THREAD

**Issue by MitchTalmadge** [openshift/openshift-java-client#245]
I was curious if there is a way to determine an application's status. For example, on the OpenShift Web Panel you can see that the status is "Started":

![image](https://cloud.githubusercontent.com/assets/8848080/16802723/76777b6a-48bf-11e6-9481-4b189db5049f.png)

I can't seem to figure out how to determine the status using this client (or rhc, for that matter). Thanks for any help!

**Comment by MitchTalmadge** [comment]
I found you can do `rhc app show --state <app-name>` to get the application status with rhc. No way I see to do this with this client.

**Comment by adietish** [comment]
Hi Mitch

Please note that this library for OpenShift 2 is not actively supported (no work on it beside critical blockers) any more. All efforts moved over to OpenShift 3. OpenShift 3 is available in source and will get available for public consumption in an online service soon. You can find the client library for OpenShift 3 here: https://github.com/openshift/openshift-restclient-java/

Full user convenience was planned but not implemented when all efforts moved off this library. You can still achieve what you're aiming at with a little manual work:
The application state is reflected in the state of the gear(s) that the application is running on. If you have your application instance you can do the following (not tested, freely pasted):
Collection<IGearGroup> gearGroups = application.getGearGroups();
for (IGearGroup gearGroup : gearGroups) {
    for (IGear gear : gearGroup.getGears()) {
         // if all gears are running your app is fully running
         IGearState state = gear.getState();
    }

**Comment by MitchTalmadge** [comment]
Ah, thanks so much :)
